### ISSUE TITLE
What do I need for 'RESPONSE_AUDIO_FILE_URL' in the 'settings.py'

### ISSUE THREAD

**Issue by DeviousPenguin** [declension/squeeze-alexa#123]
Hi I'm currently going thru the `HOWTO.md` and it says to fill out the `settings.py` file.

I'm unsure what to put in for the `RESPONSE_AUDIO_FILE_URL` setting, the HOWTO makes no mention of what mp3 file to put where, do I need to upload an MP3 to amazon somehow? Or is it better to host the mp3 myself?

Also when will the MP3 play? Will the Echo play the MP3 file on an error or when runs the squeezebox skill? Or can I just leave the setting alone for now. Thanks

**Comment by declension** [comment]
Yes, it's a little bit of a secret setting. Allows you to customise the feedback sound. I like(d) mine to be a "sci-fi computer sound".  For Amazon reasons, it needs to be on HTTPS, and I recommend it's a smallish file.

(Public) S3 hosting is perfect for this, upload to S3 then use the https endpoint to the file.

> Also when will the MP3 play? Will the Echo play the MP3 file on an error or when runs the squeezebox skill? 

No, it generally runs when it's useful (it's semi-intelligent) and only in successful interactions.

> Or can I just leave the setting alone for now. Thanks

Yes it should also work as-is, it'll just be silence (and charged to me, though negligible I think)

**Comment by DeviousPenguin** [comment]
Thanks very much, that makes things much clearer. :)

I'm still working my way around AWS right now and trying to get it to deploy, once that is done I'll play around with the extras such as custom sounds.

I did search first about this setting before posting here  and found this handy site: https://www.jovo.tech/audio-converter

It converts your sound to the correct format for Alexa and hosts it on HTTPS for 24hours, could handy for quickly testing out custom sounds before commiting it to S3/other hosting.
