### ISSUE TITLE
Update intents JSON file to new schema

### ISSUE THREAD

**Issue by declension** [declension/squeeze-alexa#23]
They've only gone and changed it. Looks more like this now:
```javascript
{
  "languageModel": {
    "intents": [
      {
        "name": "AMAZON.CancelIntent",
        "samples": []
      },
      {
        "name": "AMAZON.HelpIntent",
        "samples": []
      },
      {
        "name": "AMAZON.PauseIntent",
        "samples": []
      },
      {
        "name": "AMAZON.ResumeIntent",
        "samples": []
      },
      {
        "name": "AMAZON.StopIntent",
        "samples": []
      }
    ],
    "invocationName": "squeezebox"
  }
}
```

There's an [API for this](https://developer.amazon.com/docs/smapi/interaction-model-operations.html#update-interaction-model) it seems, or the Beta Intents editor claims to do some updating manually (but not sure it works, sigh).

**Comment by declension** [comment]
The old one is still the (only) supported schema in the original (non-beta) editor, AFAICT

**Comment by NadirJ** [comment]
Thanks for getting this project started !

**Comment by declension** [comment]
The [full interaction model schema reference](https://developer.amazon.com/docs/smapi/interaction-model-schema.html)
