### ISSUE TITLE
Provide MQTT as alternative networking

### ISSUE THREAD

**Issue by declension** [declension/squeeze-alexa#50]
It's a total re-think, but [MQTT](https://en.wikipedia.org/wiki/MQTT) was one of the original options for solving this, along with long-lived websockets etc. Raising this to track ideas as it's suddenly more important to me :smile: 

### Pros
* Can get most firewalls
* Much less configuration needed
* Allows people on [Carrier-Grade NAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT) (me now!) e.g. 3G / 4G connections to have a chance of networking
* Could work for [those with IPv6 issues](#42) too perhaps.
* AWS support has improved loads

### Cons
* Slower / more latency for sure. But maybe not too bad at all after some testing...
* More work / hassle for how much gain?
* A long-running _custom_ process would be needed, on a server, rather than a battle-tested thing like `stunnel` or Nginx...
* This means binary compilation perhaps, package management across different platforms (Linux, Synology, etc)
* More decisions for users to have to think about
* How would you manage 2-way communication as LMS CLI uses a fair bit.
* Transport layer serialisation (JSON?) needed, maybe. Or maybe not...

**Comment by frelev** [comment]
Sounds interesting, I have MQTT up and running (local broker) if you need something to be tested

**Comment by declension** [comment]
Thanks. It needs to be the AWS one really - anything local is just _different_ networking hassle (and doesn't solve my use case), and anything cloud but not AWS is workable, just too much hassle / cost. 

Also, I managed to get CLI tests working fairly easily. Won't have any time to play with this for a while but the concept seems good
