### ISSUE TITLE
How can i contribute to add German words

### ISSUE THREAD

**Issue by dersch81** [declension/squeeze-alexa#58]
Hi, i'm actually starting to add Alexa to my home automation with FHEM. Still searching for a good WAF usecase to control our LMS system, too. PI nodes are added frequently to the most rooms I actually renovate. So I would like to use your skill besides FHEM to control LMS. I also could use FHEM for LMS control but with Alexa it seems to be more complicated as to use a dedicated skill. Therefore I would like to support you. Can you tell me what I have to translate to use the skill in families native language German?

**Comment by declension** [comment]
Hi
I don't really know abou FHEM and I'm not sure which WAF you mean here. Anyway...

* German as an output language is already mostly supported (thanks to #44 and then @DFranzen in #45), you just need to set your locale to `de_DE` (raise a bug if this is broken though). 
* The _documentation_ (HOWTO, README etc) is all in English - it might be useful to translate that some time too
* The debug output / logs are all in in English too. This could be internationalised then translated as per the rest of the code (output etc), but not sure how useful that would be.

If you know all this and are looking to translate missing words (using [gettext](https://www.gnu.org/software/gettext/) tools), a PR is bes - see the guide I wrote in [CONTRIBUTING].

**Comment by declension** [comment]
@dersch81 does that help?
I'll close this ticket. If there's anything not covered we can re-open it.
