### ISSUE TITLE
Question about utterances

### ISSUE THREAD

**Issue by chatainsim** [declension/squeeze-alexa#69]
Hello,

I have a question about utterances.txt translation.

Regarding PlayRandomMixIntent part, in french, we can call for blues or jazz like this:
```du blues et du jazz```
But for pop or country we say:
```de la pop et de la country```

We also have:
```de l'acide jazz```

Is it possible to define a multiple possibility like ```[du|de la|de l']``` in the utterances.txt file ?

**Comment by declension** [comment]
> Is it possible to define a multiple possibility like [du|de la|de l'] in the utterances.txt file ?

No I don't think so, but you can just define lots and lots in the file

e.g. 
```
du {genre}
de la {genre}
```
and I've just noticed this is exactly what you did :)

Anyway, it's not worth thinking about the text file any more, as the future is `v1` Interactions, which have the utterances in the JSON file. See the [new intents.json](https://github.com/declension/squeeze-alexa/blob/master/metadata/intents/v1/locale/en_US/intents_v1.json).
